{% set name = "threeml" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#    git_url: https://github.com/giacomov/3ML.git
  path: ../../../

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - numpy >=1.6
#    - xspec-modelsonly-lite

  host:
    - python
    - numpy >=1.6
    - scipy >=0.18
    - emcee
    - astropy >=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml==3.13
    - dill
    - iminuit >=1.2
    - astromodels
    - astroquery
    - corner >=1.0.2
    - pandas
    - requests
    - speclite
    - pymultinest
    - pygmo >=2.4
    - ipywidgets
    - ipython
    - ipyparallel
    - openssl

  run:
    - python
    - numpy >=1.6
    - scipy >=0.18
    - emcee
    - astropy >=1.0.3
    - matplotlib
    - uncertainties
    - pyyaml==3.13
    - dill
    - iminuit >=1.2
    - astromodels
    - astroquery
    - corner >=1.0.2
    - pandas
    - requests
    - speclite
    - pymultinest
    - pygmo >=2.4
    - ipywidgets
    - ipython
    - ipyparallel
    - openssl



build:
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [win]
  skip: true  # [py3k]


    
#test:
#  # Python imports
#  commands:
#    - python -c 'import os;os.environ["MPLBACKEND"]="Agg";from threeML import *'


about:
  home: https://github.com/threeML/threeml
  license: BSD-3
  summary: 'The Multi-Mission Maximum Likelihood framework'
  license_family: BSD

extra:
  recipe-maintainers:
    - giacomov
    - grburgess
    

