package:
  name: cthreeml
  version: "1.0.3"

source:
  git_url: https://github.com/threeML/cthreeML.git

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}



  host:
#    - toolchain
    - python x.x
    - boost <1.65
#    - numpy
#    - gcc

  run:
    - python x.x
    - boost <1.65
    - numpy
 #   - libgcc

test:
  commands:
  
    - conda inspect linkages -p $PREFIX cthreeml  # [not win]
    - conda inspect objects -p $PREFIX cthreeml  # [osx]

  imports:
    - cthreeML.pyModelInterfaceCache


about:
  home: https://github.com/threeML/cthreeML
  license: BSD-3
  summary: 'The C/C++ bridge for the Multi-Mission Maximum Likelihood framework (github.com/giacomov/3ML)'
  license_family: BSD

extra:
  recipe-maintainers:
    - giacomov

